AWSTemplateFormatVersion: '2010-09-09'
Description: Real time event processing pipeline
Resources:
  Bridge:
    Properties:
      CodeUri: s3://sdghs-ecomm-aws-dev-sandbox/d7563ce3566d81af80ffa8349803c4f2
      Description: 'Bridge between Kinesis and Step Function execution

        '
      Environment:
        Variables:
          STATE_MACHINE_ARN:
            Ref: MyStateMachine
      Events:
        Stream:
          Properties:
            BatchSize: 100
            StartingPosition: TRIM_HORIZON
            Stream:
              Fn::GetAtt:
              - RawStream
              - Arn
          Type: Kinesis
      Handler: pipeline.bridge::handleRequest
      MemorySize: 512
      Policies:
        Statement:
        - Action:
          - logs:*
          - cloudwatch:*
          - kinesis:*
          - sns:*
          - sqs:*
          - states:*
          - lambda:*
          Effect: Allow
          Resource: '*'
      Runtime: java8
      Timeout: 10
    Type: AWS::Serverless::Function
  Decode:
    Properties:
      CodeUri: s3://sdghs-ecomm-aws-dev-sandbox/d7563ce3566d81af80ffa8349803c4f2
      Description: 'Decodes an array of messages

        '
      Handler: pipeline.decode::handleRequest
      MemorySize: 512
      Policies:
        Statement:
        - Action:
          - logs:*
          - cloudwatch:*
          - kinesis:*
          - sns:*
          - sqs:*
          Effect: Allow
          Resource: '*'
      Runtime: java8
      Timeout: 10
    Type: AWS::Serverless::Function
  Filter:
    Properties:
      CodeUri: s3://sdghs-ecomm-aws-dev-sandbox/d7563ce3566d81af80ffa8349803c4f2
      Description: 'Filters JSON blobs from a kinesis payload or pushes failed attempts
        to SNS for retry

        '
      Handler: pipeline.filter::handleRequest
      MemorySize: 512
      Policies:
        Statement:
        - Action:
          - logs:*
          - cloudwatch:*
          - kinesis:*
          - sns:*
          - sqs:*
          Effect: Allow
          Resource: '*'
      Runtime: java8
      Timeout: 10
    Type: AWS::Serverless::Function
  MyStateMachine:
    Properties:
      DefinitionString:
        Fn::Sub:
        - "{\n  \"Comment\": \"A Hello World AWL example using an AWS Lambda function\"\
          ,\n  \"StartAt\": \"Filter\",\n  \"States\": {\n    \"Filter\": {\n    \
          \  \"Type\": \"Task\",\n      \"Resource\": \"${filterArn}\",\n      \"\
          Next\": \"Decode\"\n    },\n    \"Decode\": {\n      \"Type\": \"Task\"\
          ,\n      \"Resource\": \"${lambdaArn}\",\n      \"End\": \"True\"\n    }\n\
          \  }\n}"
        - decodeArn:
            Fn::GetAtt:
            - Decode
            - Arn
          filterArn:
            Fn::GetAtt:
            - Filter
            - Arn
      RoleArn:
        Fn::GetAtt:
        - StatesExecutionRole
        - Arn
    Type: AWS::StepFunctions::StateMachine
  RawStream:
    Properties:
      RetentionPeriodHours: 24
      ShardCount: 1
      Tags:
      - Key: Project
        Value: DataScience
    Type: AWS::Kinesis::Stream
  StatesExecutionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - Fn::Sub: states.${AWS::Region}.amazonaws.com
        Version: 2012-10-17
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - lambda:InvokeFunction
            Effect: Allow
            Resource: '*'
          Version: 2012-10-17
        PolicyName: StatesExecutionPolicy
    Type: AWS::IAM::Role
Transform: AWS::Serverless-2016-10-31
