AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A lambda trigger for an EMR cluster
Resources:

  ProcessRawStream:
    Type: AWS::Serverless::Function
    Properties:
      Handler: pipeline.process_raw_stream::handleRequest
      Description: Reads events from a Kinesis stream, attempts to process | pushes failed events to SNS
      Runtime: java8
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - logs:*
              - cloudwatch:*
              - kinesis:*
              - sns:*
              - sqs:*
            Resource: "*"
      MemorySize: 512
      Timeout: 10
      CodeUri: target/pipeline-0.1.0-SNAPSHOT-standalone.jar
      Environment:
        Variables:
          SNS_ARN: !Ref RetryTopic
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !GetAtt RawStream.Arn
            BatchSize: 100
            StartingPosition: TRIM_HORIZON

  RawStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1
      RetentionPeriodHours: 24 # Hours
      Tags:
        -
          Key: Project
          Value: DataScience

#  ProcessedStream:
#    Type: AWS::Kinesis::Stream
#    Properties:
#      ShardCount: 1
#      RetentionPeriodHours: 24 # Hours
#      Tags:
#        -
#          Key: Project
#          Value: DataScience

  RetryStream:
    Type: AWS::Serverless::Function
    Properties:
      Handler: pipeline.retry_stream::handleRequest
      Description: Consumes events from SNS, attempts again to process | pushes dead DL's to SQS
      Runtime: java8
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - logs:*
              - cloudwatch:*
              - kinesis:*
              - sns:*
              - sqs:*
            Resource: "*"
      MemorySize: 512
      Timeout: 10
      CodeUri: target/pipeline-0.1.0-SNAPSHOT-standalone.jar
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt DeadLetterQueue.Arn
      Events:
        Topic:
          Type: SNS
          Properties:
            Topic: !Ref RetryTopic

  RetryTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: DataSciencePOC
      TopicName: DataSciencePOC
      Subscription:
        -
          Endpoint: !GetAtt RetryStream.Arn
          Protocol: lambda

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: KinesisRetry
      MessageRetentionPeriod: 345600 # Seconds (4 days)
