AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Real time event processing pipeline
Resources:

  Bridge:
    Type: AWS::Serverless::Function
    Properties:
      Handler: pipeline.bridge::handleRequest
      Description: >
        Bridge between Kinesis and Step
        Function execution
      Runtime: java8
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - logs:*
              - cloudwatch:*
              - kinesis:*
              - sns:*
              - sqs:*
              - states:*
              - lambda:*
            Resource: "*"
      MemorySize: 512
      Timeout: 10
      CodeUri: target/pipeline-0.1.0-SNAPSHOT-standalone.jar
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt BridgeDeadLetterQueue.Arn
      Environment:
        Variables:
          STATE_MACHINE_ARN: !Ref PipelineStateMachine
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !GetAtt RawStream.Arn
            BatchSize: 100
            StartingPosition: TRIM_HORIZON

  RawStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1
      RetentionPeriodHours: 24 # Hours
      Tags:
        -
          Key: Project
          Value: DataScience

  BridgeDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: BridgeRetry
      MessageRetentionPeriod: 345600 # Seconds (4 days)

  Filter:
    Type: AWS::Serverless::Function
    Properties:
      Handler: pipeline.filter::handleRequest
      Description: >
        Filters JSON blobs from a kinesis
        payload or pushes failed attempts
        to SNS for retry
      Runtime: java8
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - logs:*
              - cloudwatch:*
              - kinesis:*
              - sns:*
              - sqs:*
            Resource: "*"
      MemorySize: 512
      Timeout: 10
      CodeUri: target/pipeline-0.1.0-SNAPSHOT-standalone.jar

  Decode:
    Type: AWS::Serverless::Function
    Properties:
      Handler: pipeline.decode::handleRequest
      Description: >
        Decodes an array of messages
      Runtime: java8
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - logs:*
              - cloudwatch:*
              - kinesis:*
              - sns:*
              - sqs:*
            Resource: "*"
      MemorySize: 512
      Timeout: 10
      CodeUri: target/pipeline-0.1.0-SNAPSHOT-standalone.jar

  PipelineStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      DefinitionString:
        !Sub
          - |-
            {
              "Comment": "Kinesis event processing pipeline",
              "StartAt": "Filter",
              "States": {
                "Filter": {
                  "Type": "Task",
                  "Resource": "${filterArn}",
                  "Next": "Decode"
                },
                "Decode": {
                  "Type": "Task",
                  "Resource": "${decodeArn}",
                  "End": true
                }
              }
            }
          - {
              filterArn: !GetAtt [ Filter, Arn ],
              decodeArn: !GetAtt [ Decode, Arn ]
            }
      RoleArn: !GetAtt [ PipelineStateMachineExecutionRole, Arn ]

  PipelineStateMachineExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !GetAtt Filter.Arn
                  - !GetAtt Decode.Arn
