AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A lambda trigger for an EMR cluster
Resources:

  Bridge:
    Type: AWS::Serverless::Function
    Properties:
      Handler: pipeline.bridge::handleRequest
      Description: >
        Bridge between Kinesis and Step
        Function execution
      Runtime: java8
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - logs:*
              - cloudwatch:*
              - kinesis:*
              - sns:*
              - sqs:*
            Resource: "*"
      MemorySize: 512
      Timeout: 10
      CodeUri: target/pipeline-0.1.0-SNAPSHOT-standalone.jar
      Environment:
        Variables:
          STATE_MACHINE_ARN: !Ref MyStateMachine
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !GetAtt RawStream.Arn
            BatchSize: 100
            StartingPosition: TRIM_HORIZON

  RawStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1
      RetentionPeriodHours: 24 # Hours
      Tags:
        -
          Key: Project
          Value: DataScience

  Filter:
    Type: AWS::Serverless::Function
    Properties:
      Handler: pipeline.filter::handleRequest
      Description: >
        Filters JSON blobs from a kinesis
        payload or pushes failed attempts
        to SNS for retry
      Runtime: java8
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - logs:*
              - cloudwatch:*
              - kinesis:*
              - sns:*
              - sqs:*
            Resource: "*"
      MemorySize: 512
      Timeout: 10
      CodeUri: target/pipeline-0.1.0-SNAPSHOT-standalone.jar

  MyStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      DefinitionString:
        !Sub
          - |-
            {
              "Comment": "A Hello World AWL example using an AWS Lambda function",
              "StartAt": "HelloWorld",
              "States": {
                "HelloWorld": {
                  "Type": "Task",
                  "Resource": "${lambdaArn}",
                  "End": true
                }
              }
            }
          - {lambdaArn: !GetAtt [ Filter, Arn ]}
      RoleArn: !GetAtt [ StatesExecutionRole, Arn ]

  StatesExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: "*"
